import type { Metadata } from "next";

// app/[lang]/layout.tsx
export async function generateStaticParams() {
  return [
    { lang: 'en' },
    { lang: 'ja' }
  ]
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  return (
    <html lang={params.lang}>
      <body>
        <header>header</header>
        <main>{children}</main>
        <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
          footer
        </footer>
      </body>
    </html>
  )
}